# Generated by Django 3.1.7 on 2021-04-11 06:03

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(default='0aa62488-3abb-4939-a779-e6e42a29c959', max_length=36, unique=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('running', 'running'), ('interrupted', 'interrupted'), ('running', 'running'), ('failed', 'failed'), ('executed', 'executed'), ('rejected', 'rejected')], default='created', max_length=32)),
                ('input_args', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('finished_by', models.DateTimeField(null=True)),
            ],
        ),
    ]
