# Generated by Django 3.1.7 on 2021-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='token',
            field=models.CharField(default='a6392a19-89d0-481f-aa84-8d06e6ccf64a', max_length=36, unique=True),
        ),
    ]
