# Generated by Django 3.1.7 on 2021-04-11 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210411_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='token',
            field=models.CharField(default='98e282da-800a-4127-815d-4702343332a4', max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='JobLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('shell_command', models.TextField()),
                ('about', models.CharField(blank=True, default='', max_length=50)),
                ('output', models.TextField()),
                ('error', models.TextField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50)),
                ('input_args', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('any_error', models.BooleanField(default=False)),
                ('executed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.job')),
            ],
        ),
    ]
