# Generated by Django 3.1.7 on 2021-04-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210411_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='token',
            field=models.CharField(default='bae92712-4e4c-4539-ba1e-fbac49040a50', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='joblogs',
            name='error',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='joblogs',
            name='output',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
